export const CONFIG = {
    MODEL_PATH: 'assets/10k.glb',
    MODEL_PATH_1K: 'assets/500.glb',
    SOUNDS: {
        BURP: 'assets/otryijka.mp3',
        GAG: 'assets/rvotnyiy-pozyiv.mp3',
        PSX: 'assets/psx.mp3'
    },
    CLICK_THRESHOLD: 500,
    CLICKS_FOR_GAG: 3,
    DEFORM_THROTTLE: 16.67, // ~60fps
    DEFORM_RADIUS: 3.0,
    DEFORM_STRENGTH: 0.8,
    RETURN_DAMPING: 0.75,
    RETURN_SPRING: 0.2,
    MOBILE_BREAKPOINT: 768,
    MOBILE_SCALE: 1.4,
    DESKTOP_SCALE: 2.0,
    MOBILE_Z: 0.7,
    DESKTOP_Z: 1.0,
    AMBIENT_LIGHT_INTENSITY: 1.2,
    MAIN_LIGHT_INTENSITY: 1.6,
    DYNAMIC_LIGHT_INTENSITY: 100,
    DISCO_LIGHT_INTENSITY: 100,
    DISCO_LIGHT_HUE_SPEED: 0.0003,
    DISCO_LIGHT_MOVE_SPEED: 0.001,
    DISCO_LETTER_HUE_SPEED: 0.0002,
    MOUSE_ROTATION_X_FACTOR: 0.3,
    MOUSE_ROTATION_Y_FACTOR: 0.5,
    LERP_FACTOR: 0.05,
    RETURN_LERP_FACTOR: 0.2,
    GRAB_LERP_FACTOR: 0.6
};
